### ISSUE TITLE
Typo in JPQL query in the abstract method of Work Repository Layer

### ISSUE THREAD

**Issue by sparrowline** [sparrowline/HomeServeO#1]
In the abstract method of the Work Repository Layer, there is a typographical error in the JPQL query within the @Query annotation. The incorrect query is: @Query("select a from Work where a.startDate=null"). The correct query should be: @Query("select a from Work a where a.startDate is null")

**Comment by Anupam2528** [comment]
Hey @sparrowline 
Can I fix this?

**Comment by Anupam2528** [comment]
Created PR..
